export enum TelemetryEvent {
  SEARCH_EXECUTED = 'SEARCH_EXECUTED',
  SEARCH_RESULT_CLICKED = 'SEARCH_RESULT_CLICKED',
  IPC_ERROR = 'IPC_ERROR',
}

export enum TelemetryMetric {
  SEARCH_LATENCY_MS = 'SEARCH_LATENCY_MS',
  BLOB_LOAD_TIME_MS = 'BLOB_LOAD_TIME_MS',
}
