export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  SEARCH_ENGINE_ERROR = 'SEARCH_ENGINE_ERROR',
  DOC_FORMAT_UNSUPPORTED = 'DOC_FORMAT_UNSUPPORTED',
  DIP_CORRUPT_ARCHIVE = 'DIP_CORRUPT_ARCHIVE',
  IPC_ERROR = 'IPC_ERROR',
  DOC_BLOB_LOAD_ERROR = 'DOC_BLOB_LOAD_ERROR',
  DIP_PARSE_ERROR = 'DIP_PARSE_ERROR',
  DIP_INDEX_ERROR = 'DIP_INDEX_ERROR',
  INTEGRITY_VERIFY_ERROR = 'INTEGRITY_VERIFY_ERROR',
  LOAD_CHILDREN_FAILED = 'LOAD_CHILDREN_FAILED',
}

export enum ErrorCategory {
  IPC = 'IPC',
  VALIDATION = 'VALIDATION',
  DOMAIN = 'DOMAIN',
  IO = 'IO',
  PRINT = 'PRINT',
}

export enum ErrorSeverity {
  FATAL = 'FATAL',
  ERROR = 'ERROR',
  WARNING = 'WARNING',
  INFO = 'INFO',
}
