name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install
          cd core && npm install && cd ..
          cd renderer && npm install && cd ..

      - name: Build project
        run: |
          npm run build:all

      - name: Run Tests and Coverage
        run: |
          # Test Renderer (Angular)
          npm run test:renderer

          # Test Core (Electron)
          npm run test:core

      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=dipreader
            -Dsonar.projectName=dipreader
            -Dsonar.sources=core,renderer/src,shared,main.ts
            -Dsonar.tests=core,renderer/src
            -Dsonar.test.inclusions=**/*.spec.ts,**/*.test.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.typescript.tsconfigPath=tsconfig.json
            -Dsonar.sourceEncoding=UTF-8
